version: '3'

services:
  db:
    image: mysql:$MYSQL_VERS
    container_name: db
    restart: unless-stopped
    env_file: $ENV_DIR/db/.env
    volumes: 
      - $DATA_DIR/db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp-network

  wp:
    depends_on:
      - db
    image: wordpress:$WP_VERS
    container_name: wp
    restart: unless-stopped
    env_file: $ENV_DIR/wp/.env
    volumes:
      - $DATA_DIR/web:/var/www/html
    networks:
      - wp-network

  web:
    depends_on:
      - wp
    image: nginx:$NGINX_VERS
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $DATA_DIR/web:/var/www/html
      - $CONF_DIR/web:/etc/nginx/conf.d
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge